#=using Pkg, JLD2, Random
Pkg.activate("../")
Pkg.pin(name = "JLD2", version = "0.1.11")
push!(LOAD_PATH, pwd())
using HANKEstim=#
# sr = JLD2.jldopen("7_Saves/steadystate_seed1793.jld2", "r")["sr"]

# JLD2.jldopen("bbl_unwrapped_steadystate.jld2", true, true, true, IOStream) do file
JLD2.jldopen("compute_steadystate_output_seed1793.jld2", true, true, true, IOStream) do file
    write(file, "marginal_pdf_m_star", sr.XSS[sr.indexes.distr_m_SS])
    write(file, "marginal_pdf_k_star", sr.XSS[sr.indexes.distr_k_SS])
    write(file, "marginal_pdf_y_star", sr.XSS[sr.indexes.distr_y_SS])
    write(file, "distr_star", sr.XSS[sr.indexes.DSS])
    write(file, "Vm_star", sr.XSS[sr.indexes.VmSS])
    write(file, "Vk_star", sr.XSS[sr.indexes.VkSS])
#=    write(file, "dct_copula_star", sr.XSS[sr.indexes.D])
    write(file, "dct_Vm_star", sr.XSS[sr.indexes.Vm])
    write(file, "dct_Vk_star", sr.XSS[sr.indexes.Vk])=#
    write(file, "A_star", sr.XSS[sr.indexes.ASS])
    write(file, "Z_star", sr.XSS[sr.indexes.ZSS])
    write(file, "Psi_star", sr.XSS[sr.indexes.ZISS])
    write(file, "mu_p_star", sr.XSS[sr.indexes.μSS])
    write(file, "mu_w_star", sr.XSS[sr.indexes.μwSS])
    write(file, "sigma_star", sr.XSS[sr.indexes.σSS])
    write(file, "union_retained_star", sr.XSS[sr.indexes.union_RetainedSS])
    write(file, "retained_star", sr.XSS[sr.indexes.RetainedSS])
    write(file, "Y_l1_star", sr.XSS[sr.indexes.YlagSS])
    write(file, "B_l1_star", sr.XSS[sr.indexes.BlagSS])
    write(file, "T_l1_star", sr.XSS[sr.indexes.TlagSS])
    write(file, "I_l1_star", sr.XSS[sr.indexes.IlagSS])
    write(file, "w_l1_star", sr.XSS[sr.indexes.wlagSS])
    write(file, "q_l1_star", sr.XSS[sr.indexes.qlagSS])
    write(file, "C_l1_star", sr.XSS[sr.indexes.ClagSS])
    write(file, "avg_tax_rate_l1_star", sr.XSS[sr.indexes.av_tax_ratelagSS])
    write(file, "tau_prog_l1_star", sr.XSS[sr.indexes.τproglagSS])
    write(file, "G_sh_star", sr.XSS[sr.indexes.GshockSS])
    write(file, "R_sh_star", sr.XSS[sr.indexes.RshockSS])
    write(file, "S_sh_star", sr.XSS[sr.indexes.SshockSS])
    write(file, "P_sh_star", sr.XSS[sr.indexes.TprogshockSS])
    write(file, "rk_star", sr.XSS[sr.indexes.rSS])
    write(file, "w_star", sr.XSS[sr.indexes.wSS])
    write(file, "K_star", sr.XSS[sr.indexes.KSS])
    write(file, "pi_star", sr.XSS[sr.indexes.πSS])
    write(file, "pi_w_star", sr.XSS[sr.indexes.πwSS])
    write(file, "Y_star", sr.XSS[sr.indexes.YSS])
    write(file, "C_star", sr.XSS[sr.indexes.CSS])
    write(file, "q_star", sr.XSS[sr.indexes.qSS])
    write(file, "N_star", sr.XSS[sr.indexes.NSS])
    write(file, "mc_star", sr.XSS[sr.indexes.mcSS])
    write(file, "mc_w_star", sr.XSS[sr.indexes.mcwSS])
    write(file, "u_star", sr.XSS[sr.indexes.uSS])
    write(file, "Ht_star", sr.XSS[sr.indexes.HtSS])
    write(file, "avg_tax_rate_star", sr.XSS[sr.indexes.av_tax_rateSS])
    write(file, "T_star", sr.XSS[sr.indexes.TSS])
    write(file, "I_star", sr.XSS[sr.indexes.ISS])
    write(file, "B_star", sr.XSS[sr.indexes.BSS])
    write(file, "BD_star", sr.XSS[sr.indexes.BDSS])
    write(file, "BY_star", sr.XSS[sr.indexes.BYSS])
    write(file, "TY_star", sr.XSS[sr.indexes.TYSS])
    write(file, "mc_w_w_star", sr.XSS[sr.indexes.mcwwSS])
    write(file, "G_star", sr.XSS[sr.indexes.GSS])
    write(file, "tau_level_star", sr.XSS[sr.indexes.τlevSS])
    write(file, "tau_prog_star", sr.XSS[sr.indexes.τprogSS])
    write(file, "Gini_C_star", sr.XSS[sr.indexes.GiniCSS])
    write(file, "Gini_X_star", sr.XSS[sr.indexes.GiniXSS])
    write(file, "sd_log_y_star", sr.XSS[sr.indexes.sdlogySS])
    write(file, "I90_share_star", sr.XSS[sr.indexes.I90shareSS])
    write(file, "I90_share_net_star", sr.XSS[sr.indexes.I90sharenetSS])
    write(file, "W90_share_star", sr.XSS[sr.indexes.w90shareSS])
    write(file, "Ygrowth_star", sr.XSS[sr.indexes.YgrowthSS])
    write(file, "Bgrowth_star", sr.XSS[sr.indexes.BgrowthSS])
    write(file, "Tgrowth_star", sr.XSS[sr.indexes.TgrowthSS])
    write(file, "Igrowth_star", sr.XSS[sr.indexes.IgrowthSS])
    write(file, "wgrowth_star", sr.XSS[sr.indexes.wgrowthSS])
    write(file, "Cgrowth_star", sr.XSS[sr.indexes.CgrowthSS])
    write(file, "LP_star", sr.XSS[sr.indexes.LPSS])
    write(file, "LP_XA_star", sr.XSS[sr.indexes.LPXASS])
    write(file, "tot_retained_Y_star", sr.XSS[sr.indexes.totRetainedYSS])
    write(file, "union_firm_profits_star", sr.XSS[sr.indexes.union_firm_profitsSS])
    write(file, "union_profits_star", sr.XSS[sr.indexes.unionprofitsSS])
    write(file, "firm_profits_star", sr.XSS[sr.indexes.firm_profitsSS])
    write(file, "profits_star", sr.XSS[sr.indexes.profitsSS])
    write(file, "dct_compression_indices_Vm", sr.compressionIndexes[1])
    write(file, "dct_compression_indices_Vk", sr.compressionIndexes[2])
    write(file, "dct_compression_indices_copula", sr.compressionIndexes[3])
end
